#!/usr/bin/env bash
# agent-chrome-setup.sh — Install headless Chrome in a restricted sandbox (no root/sudo)
# Part of XanLens. Safe to run multiple times (idempotent).
set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────────
BREW_PREFIX="${HOMEBREW_PREFIX:-/home/linuxbrew/.linuxbrew}"
MIN_DISK_MB=500          # minimum free disk to attempt mesa/llvm
PLAYWRIGHT_BROWSERS_PATH="${PLAYWRIGHT_BROWSERS_PATH:-$HOME/.cache/ms-playwright}"
export NONINTERACTIVE=1  # for brew installer

# ── Helpers ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { printf "${CYAN}[chrome-setup]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[✓]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[!]${NC} %s\n" "$*"; }
err()  { printf "${RED}[✗]${NC} %s\n" "$*"; }

free_disk_mb() {
  df -m "${1:-.}" 2>/dev/null | awk 'NR==2{print $4}' || echo 0
}

elapsed() {
  local s=$1
  printf "%dm%ds" $((s/60)) $((s%60))
}

# ── Step 1: Homebrew ─────────────────────────────────────────────────────────
install_brew() {
  if command -v brew &>/dev/null; then
    ok "Homebrew already installed ($(brew --prefix))"
    BREW_PREFIX="$(brew --prefix)"
    return 0
  fi

  log "Installing Homebrew (Linuxbrew)..."
  local start=$SECONDS
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" </dev/null

  # Add to PATH for this session
  if [[ -x "$BREW_PREFIX/bin/brew" ]]; then
    eval "$("$BREW_PREFIX/bin/brew" shellenv)"
  elif [[ -x "$HOME/.linuxbrew/bin/brew" ]]; then
    BREW_PREFIX="$HOME/.linuxbrew"
    eval "$("$BREW_PREFIX/bin/brew" shellenv)"
  fi

  if ! command -v brew &>/dev/null; then
    err "Homebrew installation failed"
    return 1
  fi
  BREW_PREFIX="$(brew --prefix)"
  ok "Homebrew installed in $(elapsed $((SECONDS-start)))"
}

# ── Step 2: Chrome dependencies via brew ─────────────────────────────────────
BREW_PACKAGES=(
  dbus at-spi2-core atk cups
  libxcomposite libxdamage libxfixes libxrandr libxkbcommon
  alsa-lib libxi libxcursor
  gtk+3
)
# mesa is separate — it pulls llvm which is huge
MESA_PACKAGES=(mesa)

install_deps() {
  log "Installing Chrome dependencies via brew..."
  local start=$SECONDS
  local failed=()

  for pkg in "${BREW_PACKAGES[@]}"; do
    if brew list --formula "$pkg" &>/dev/null; then
      continue
    fi
    log "  Installing $pkg..."
    if ! brew install --formula "$pkg" 2>&1 | tail -1; then
      warn "Failed to install $pkg — continuing"
      failed+=("$pkg")
    fi
  done

  # Mesa/LLVM — conditional on disk space
  local disk_mb
  disk_mb=$(free_disk_mb "$BREW_PREFIX")
  if brew list --formula mesa &>/dev/null; then
    ok "mesa already installed"
  elif (( disk_mb < MIN_DISK_MB )); then
    warn "Skipping mesa (need ${MIN_DISK_MB}MB free, have ${disk_mb}MB) — Chrome may still work"
  else
    log "  Installing mesa (this pulls LLVM, may take a while)..."
    if ! brew install --formula mesa 2>&1 | tail -1; then
      warn "mesa/LLVM install failed — skipping (Chrome may still work without it)"
    fi
  fi

  if (( ${#failed[@]} > 0 )); then
    warn "Some packages failed: ${failed[*]}"
  fi
  ok "Dependencies installed in $(elapsed $((SECONDS-start)))"
}

# ── Step 3: LD_LIBRARY_PATH ─────────────────────────────────────────────────
setup_ld_path() {
  local paths=()

  # Brew lib directories
  paths+=("$BREW_PREFIX/lib")
  # Individual package lib dirs (some packages install to their own prefix)
  for dir in "$BREW_PREFIX"/opt/*/lib; do
    [[ -d "$dir" ]] && paths+=("$dir")
  done

  # Playwright Firefox bundled libs (nss, nspr, etc.)
  for dir in "$PLAYWRIGHT_BROWSERS_PATH"/firefox-*/; do
    [[ -d "$dir" ]] && paths+=("$dir")
  done

  local ld_path
  ld_path=$(IFS=:; echo "${paths[*]}")

  # Prepend existing LD_LIBRARY_PATH if set
  if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
    ld_path="$ld_path:$LD_LIBRARY_PATH"
  fi

  export LD_LIBRARY_PATH="$ld_path"

  # Write env file for other tools to source
  local env_file="$HOME/.chrome-sandbox-env"
  cat > "$env_file" <<EOF
# Generated by agent-chrome-setup.sh — source this for headless Chrome
export LD_LIBRARY_PATH="$ld_path"
export PLAYWRIGHT_BROWSERS_PATH="$PLAYWRIGHT_BROWSERS_PATH"
eval "\$("$BREW_PREFIX/bin/brew" shellenv)"
EOF
  ok "LD_LIBRARY_PATH configured ($(echo "$ld_path" | tr ':' '\n' | wc -l) dirs)"
  ok "Env file written to $env_file"
}

# ── Step 4: Playwright + Chromium ────────────────────────────────────────────
install_playwright() {
  if ! command -v npx &>/dev/null; then
    err "npx not found — need Node.js installed"
    return 1
  fi

  # Install playwright if not present
  if ! npx playwright --version &>/dev/null 2>&1; then
    log "Installing Playwright..."
    npm install -g playwright 2>&1 | tail -3
  fi

  # Install Chromium browser if not present
  local chromium_dir
  chromium_dir=$(find "$PLAYWRIGHT_BROWSERS_PATH" -maxdepth 1 -name 'chromium-*' -type d 2>/dev/null | head -1)
  if [[ -n "$chromium_dir" ]] && [[ -x "$chromium_dir/chrome-linux/chrome" || -x "$chromium_dir/chrome-linux/headless_shell" ]]; then
    ok "Playwright Chromium already installed"
  else
    log "Installing Playwright Chromium..."
    npx playwright install chromium 2>&1 | tail -3
    # Also install Firefox for its bundled libs (nss etc.)
    log "Installing Playwright Firefox (for bundled libs)..."
    npx playwright install firefox 2>&1 | tail -3
  fi
  ok "Playwright ready"
}

# ── Step 5: Test ─────────────────────────────────────────────────────────────
test_chrome() {
  log "Testing headless Chrome launch..."

  # Find the chromium binary
  local chrome_bin=""
  for f in "$PLAYWRIGHT_BROWSERS_PATH"/chromium-*/chrome-linux/headless_shell \
           "$PLAYWRIGHT_BROWSERS_PATH"/chromium-*/chrome-linux/chrome; do
    [[ -x "$f" ]] && chrome_bin="$f" && break
  done

  if [[ -z "$chrome_bin" ]]; then
    err "Could not find Chromium binary in $PLAYWRIGHT_BROWSERS_PATH"
    return 1
  fi

  log "  Binary: $chrome_bin"

  # Quick launch test
  local output
  if output=$("$chrome_bin" --headless --no-sandbox --disable-gpu --dump-dom "data:text/html,<h1>OK</h1>" 2>&1); then
    if echo "$output" | grep -q "OK"; then
      ok "Chrome launched successfully!"
      return 0
    fi
  fi

  # Check for missing libs
  local missing
  missing=$(ldd "$chrome_bin" 2>/dev/null | grep "not found" || true)
  if [[ -n "$missing" ]]; then
    warn "Missing shared libraries:"
    echo "$missing" | head -10
    warn "Try: source ~/.chrome-sandbox-env && run your command"
  fi

  err "Chrome test failed"
  echo "$output" | tail -5
  return 1
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
  echo ""
  printf "${CYAN}╔══════════════════════════════════════════════╗${NC}\n"
  printf "${CYAN}║  XanLens — Headless Chrome Sandbox Installer ║${NC}\n"
  printf "${CYAN}╚══════════════════════════════════════════════╝${NC}\n"
  echo ""

  local total_start=$SECONDS

  install_brew
  install_deps
  setup_ld_path
  install_playwright
  echo ""

  if test_chrome; then
    echo ""
    printf "${GREEN}╔══════════════════════════════════════════════╗${NC}\n"
    printf "${GREEN}║  ✓ Chrome is ready! No root required.        ║${NC}\n"
    printf "${GREEN}║                                              ║${NC}\n"
    printf "${GREEN}║  Source env:  source ~/.chrome-sandbox-env   ║${NC}\n"
    printf "${GREEN}╚══════════════════════════════════════════════╝${NC}\n"
    ok "Total time: $(elapsed $((SECONDS-total_start)))"
    return 0
  else
    echo ""
    printf "${RED}╔══════════════════════════════════════════════╗${NC}\n"
    printf "${RED}║  ✗ Chrome setup incomplete                   ║${NC}\n"
    printf "${RED}║  Check missing libs above and retry.         ║${NC}\n"
    printf "${RED}╚══════════════════════════════════════════════╝${NC}\n"
    return 1
  fi
}

main "$@"
